Id:             'bluebeamrevu-cornell'
Description:    'bluebeam revu build3'
Version:        '21.11.0'

Install:                                    ## If there are installation files in a .zip to be installed, specify here
  - File:       '%INSTALL_DIR%\Bluebeam Revu x64 21.msi'   ## Installation file
    FileType:   'msi'                       ## exe or msi are the only options currently
    Arguments:  '/qn /norestart BB_DISABLEANALYTICS=1 DISABLE_WELCOME=1 IGNORE_RBT=1 BB_DEFAULTVIEWER=0 MBCODE=26'        ## Silent installation switches/parmeters
    ExitCodes:  [0]                         ## Exit codes - returns a success
    
Applications:
    bluebeamrevu:
        DisplayName:    'Bluebeam Revu'
        Path:           '%PROGRAMFILES%\Bluebeam Software\Bluebeam Revu\Revu\Revu.exe'
        LaunchParams:   ''
        WorkDir:        ''


