Id:             'ansys-mae'
Description:    'ANSYS 2026 R1 - COECIS License - build2'
Version:        '26.1.03.0'

Install:
  - File:       '%INSTALL_DIR%\setup.exe'
    FileType:   'exe' 
    Arguments:  '-optislang -fluent -mechapdl -discoveryreduced -edupack -electromagneticssuite -licserverinfo %LIC_SERVER% -silent'
    ExitCodes:  [0]

  - File:       '%INSTALL_DIR%\SPACECLAIM_2026R1\setup.exe'
    FileType:   'exe' 
    Arguments:  '-silent'
    ExitCodes:  [0]
    
  - File:       '%INSTALL_DIR%\Ansys_STK_Enterprise_ODTK_v13.1.0\install.exe'
    FileType:   'exe' 
    Arguments:  '--silent --licenseagree'
    ExitCodes:  [0]
    
Applications:
    ANSYSWB:
        DisplayName:    'Workbench 2026 R1'
        Path:           '%PROGRAMFILES%\ANSYS Inc\v261\Framework\bin\Win64\RunWB2.exe'
        LaunchParams:   ''
        WorkDir:        ''

    SPACECLAIM:
        DisplayName:    'SpaceClaim 2026 R1'
        Path:           '%PROGRAMFILES%\ANSYS Inc\v261\scdm\SpaceClaim.exe'
        LaunchParams:   ''
        WorkDir:        ''
        
    ansysSTK:
        DisplayName:    'STK 2026 R1'
        Path:           '%PROGRAMFILES%\AGI\STK_ODTK 13\bin\AgUiApplication.exe'
        LaunchParams:   '/pers "STK"'
        WorkDir:        ''

# removed for fall 2026      
#    healthcaresimlab:
#        DisplayName:    'Academic Healthcare SimLab'
#        Path:           '%WINDIR%\System32\WindowsPowerShell\v1.0\powershell.exe'
#        LaunchParams:   '-Windowstyle Hidden -File \"%PROGRAMFILES%\ANSYS Inc\v261\Ansys AHSL\ahsl.ps1\"'
#        WorkDir:        ''

    ansysdis:
        DisplayName:    'Discovery 2026 R1'
        Path:           '%PROGRAMFILES%\ANSYS Inc\v261\Discovery\Discovery.exe'
        LaunchParams:   ''
        WorkDir:        ''
    
    electronics:
        DisplayName:    'Ansys Electronics Desktop 2026 R1'
        Path:           '%PROGRAMFILES%\Ansys Inc\v261\AnsysEM\ansysedt.exe'
        LaunchParams:   ''
        WorkDir:        ''

    ansysgrantaedu:
        DisplayName:    'Granta EduPack 2026 R1'
        Path:           '%PROGRAMFILES%\ANSYS Inc\v261\edupack\edupack.exe'
        LaunchParams:   ''
        WorkDir:        ''

    fluent:
        DisplayName:    'Ansys Fluent 2026 R1'
        Path:           '%PROGRAMFILES%\ANSYS Inc\v261\fluent\ntbin\win64\fluent.exe'
        LaunchParams:   ''
        WorkDir:        ''

    mechanical:
        DisplayName:    'Ansys Mechanical 2026 R1'
        Path:           '%PROGRAMFILES%\ANSYS Inc\v261\aisol\bin\winx64\AnsysWBU.exe'
        LaunchParams:   '-DSApplet'
        WorkDir:        ''

    optislang:
        DisplayName:    'Ansys optiSLang 2026 R1'
        Path:           '%PROGRAMFILES%\ANSYS Inc\v261\optiSLang\optislang.exe'
        LaunchParams:   ''
        WorkDir:        ''        

Files:
    #'%INSTALL_DIR%\Ansys AHSL': '%PROGRAMFILES%\ANSYS Inc\v261\Ansys AHSL' # Healthcare SimLab
   # '%TOOLS_DIR%\ahsl.ps1': '%PROGRAMFILES%\ANSYS Inc\v261\Ansys AHSL\ahsl.ps1' # Healthcare SimLab Launcher
    '%TOOLS_DIR%\UserSettings.xml': '%SYSTEMDRIVE%\Users\Default\AppData\Local\Ansys_Inc\v261\Discovery\UserSettings\UserSettings.xml'
    '%INSTALL_DIR%\ApipUserConfig.txt': '%SYSTEMDRIVE%\Users\Default\AppData\Roaming\Ansys\v261\ApipUserConfig.txt'
    '%TOOLS_DIR%\host.cfg': '%SYSTEMDRIVE%\Users\Default\Documents\Ansoft\ElectronicsDesktop2026.1\config\host.cfg'
    '%TOOLS_DIR%\host_user.xml': '%SYSTEMDRIVE%\Users\Default\Documents\Ansoft\ElectronicsDesktop2026.1\config\host_user.XML'
    #'%INSTALL_DIR%\CADConfigurationInfo.XML': '%PROGRAMFILES%\ANSYS Inc\v261\commonfiles\CAD\CADConfigurationInfo.XML'
    #'%INSTALL_DIR%\ansyslmd.ini': '%PROGRAMFILES%\ANSYS Inc\Shared Files\Licensing\ansyslmd.ini'
    
Scripts:
    start:
        System: '%TOOLS_DIR%\startup.ps1' # Runs at system startup - Update files to match system hostname
        User: '%TOOLS_DIR%\logon.ps1'     # Runs at user logon - Update project file path

Registry:               
    HKUD:               
        SOFTWARE\SpaceClaim\SIP:
            Displayed:
                Type:   'String'
                Value:  '1'
