Id:             'solidworks-coecis'
Description:    'SOLIDWORKS 2025 - COECIS'
Version:        '33.3.0.92'

Install:                                    
  - File:       '%INSTALL_DIR%\swwi\data\Solidworks.msi'
    FileType:   'msi'
    Arguments:  'INSTALLDIR="%PROGRAMFILES%\SOLIDWORKS Corp\SOLIDWORKS" SOLIDWORKSSERIALNUMBER=%SWSERIALNUMBER% ENABLEPERFORMANCE=0 OFFICEOPTION=2 TOOLBOXFOLDER="C:\SOLIDWORKS Data" ADDLOCAL=SolidWorks,SolidWorksToolbox /qn /norestart'
    ExitCodes:  [0]

  - File:       '%INSTALL_DIR%\eDrawings\eDrawings.msi'
    FileType:   'msi'
    Arguments:  'ENABLEPERFORMANCE=0 INSTALLDIR="%PROGRAMFILES%\SOLIDWORKS Corp\SOLIDWORKS\eDrawings" SOLIDWORKSSERIALNUMBER=%SWSERIALNUMBER% ADDLOCAL=All /qb'
    ExitCodes:  [0]

  - File:       '%INSTALL_DIR%\swpdmclient\SOLIDWORKS PDM Client.msi'
    FileType:   'msi'
    Arguments:  'ENABLEPERFORMANCE=0 INSTALLDIR="%PROGRAMFILES%\SOLIDWORKS Corp\SOLIDWORKS\SOLIDWORKS PDM Client" SOLIDWORKSSERIALNUMBER=%SWSERIALNUMBER% /qn /norestart'
    ExitCodes:  [0]

  - File:       '%INSTALL_DIR%\swComposerPlayer\SOLIDWORKS Composer Player.msi'
    FileType:   'msi'
    Arguments:  'ENABLEPERFORMANCE=0 INSTALLDIR="%PROGRAMFILES%\SOLIDWORKS Corp\SOLIDWORKS\Composer" SOLIDWORKSSERIALNUMBER=%SWSERIALNUMBER% /qn'
    ExitCodes:  [0]

  - File:       '%INSTALL_DIR%\swComposer\SOLIDWORKS Composer.msi'
    FileType:   'msi'
    Arguments:  'ENABLEPERFORMANCE=0 INSTALLDIR="%PROGRAMFILES%\SOLIDWORKS Corp\SOLIDWORKS\Composer" SOLIDWORKSSERIALNUMBER=%SWSERIALNUMBER% /qn'
    ExitCodes:  [0]
    
  - File:       '%INSTALL_DIR%\visualize\SOLIDWORKS visualize.msi'
    FileType:   'msi'
    Arguments:  'ENABLEPERFORMANCE=0 INSTALLDIR="%PROGRAMFILES%\SOLIDWORKS Corp\SOLIDWORKS\Visualize" SOLIDWORKSSERIALNUMBER=%SWSERIALNUMBER% /qn /norestart'
    ExitCodes:  [0]
    
Applications:
    SLDWORKS:
        DisplayName:    'SOLIDWORKS 2025'
        Path:           '%PROGRAMFILES%\SOLIDWORKS Corp\SOLIDWORKS\SLDWORKS.exe'
        LaunchParams:   ''
        WorkDir:        ''

    eDrawings:
        DisplayName:    'SOLIDWORKS eDrawings'
        Path:           '%PROGRAMFILES%\SOLIDWORKS Corp\SOLIDWORKS\eDrawings\eDrawings.exe'
        LaunchParams:   ''
        WorkDir:        ''
        
    Baja_Vault:
        DisplayName:    'Baja_Vault'
        Path:           '%SYSTEMDRIVE%\startbaja.cmd'
        LaunchParams:   ''
        WorkDir:        ''  
        
    composerplayer:
        DisplayName:    'SOLIDWORKS Composer Player'
        Path:           '%PROGRAMFILES%\SOLIDWORKS Corp\SOLIDWORKS\Composer\Bin\composerplayer.exe'
        LaunchParams:   ''
        WorkDir:        '' 
        
    SLDWORKSVisualize:        
        DisplayName:    'SOLIDWORKS Visualize'        
        Path:           '%PROGRAMFILES%\SOLIDWORKS Corp\SOLIDWORKS\SOLIDWORKS Visualize\SLDWORKSVisualize.exe'
        LaunchParams:   ''
        WorkDir:        ''
      
    toolbox:
        DisplayName:    'Toolbox Settings 2025'
        Path:           '%PROGRAMFILES%\SOLIDWORKS Corp\SOLIDWORKS\SldToolboxConfigure.exe'
        LaunchParams:   ''
        WorkDir:        ''

Files: 
    '%TOOLS_DIR%\solidworks-accept-eula.ps1': '%ALLUSERSPROFILE%\solidworks-accept-eula.ps1'
    '%TOOLS_DIR%\SolidWorks\*': '%SYSTEMDRIVE%\Users\Default\AppData\Local'

Services:                   ## Set default service behavior
    RemoteSolverDispatcher: 'Manual'   ## ServiceName: Behavior
    SWVisualize2025.Queue.server: 'Manual'

Scripts:
    start:
        User: '%TOOLS_DIR%\solidworks-accept-eula.ps1' # Runs at user login

Registry:
    HKLM:
        SOFTWARE\SolidWorks\Applications\PDMWorks Enterprise\Databases\Baja_Vault:
            DbName:
                Type:   'String'
                Value:  'Baja_Vault'

            DbServer:
                Type:   'String'
                Value:  '%BAJA_LICENSE%'

            ServerLoc:
                Type:   'String'
                Value:  '%BAJA_LICENSE%'

            ShellRoot:
                Type:   'String'
                Value:  '%BAJA_LICENSE%'
