Id:             'solidworks-coecis'
Description:    'SOLIDWORKS 2025 - COECIS'
Version:        '33.0.0.5050'

Install:
    File:       '%INSTALL_DIR%\startswinstall.exe'
    FileType:   'exe'
    Arguments:  '/install /now'
    ExitCodes:  [0]

Applications:
    SLDWORKS:
        DisplayName:    'SOLIDWORKS 2025'
        Path:           '%PROGRAMFILES%\SOLIDWORKS Corp\SOLIDWORKS\SLDWORKS.exe'
        LaunchParams:   ''
        WorkDir:        ''
        
    composerplayer:
        DisplayName:    'SOLIDWORKS Composer Player'
        Path:           '%PROGRAMFILES%\SOLIDWORKS Corp\Composer\bin\composerplayer.exe'
        LaunchParams:   ''
        WorkDir:        ''

    SLDWORKSVisualize:        
        DisplayName:    'SOLIDWORKS Visualize'        
        Path:           '%PROGRAMFILES%\SOLIDWORKS Corp\SOLIDWORKS Visualize\SLDWORKSVisualize.exe'
        LaunchParams:   ''
        WorkDir:        ''

    eDrawings:
        DisplayName:    'SOLIDWORKS eDrawings'
        Path:           '%PROGRAMFILES%\SOLIDWORKS Corp\eDrawings\eDrawings.exe'
        LaunchParams:   ''
        WorkDir:        ''
        
    toolbox:
        DisplayName:    'Toolbox Settings 2025'
        Path:           '%PROGRAMFILES%\SOLIDWORKS Corp\SOLIDWORKS\SldToolboxConfigure.exe'
        LaunchParams:   ''
        WorkDir:        ''

Files: 
    '%TOOLS_DIR%\solidworks-accept-eula.ps1': '%ALLUSERSPROFILE%\solidworks-accept-eula.ps1'
    '%TOOLS_DIR%\SolidWorks\*': '%SYSTEMDRIVE%\Users\Default\AppData\Local'

Services:                   ## Set default service behavior
 #   RemoteSolverDispatcher: 'Manual'   ## ServiceName: Behavior
    SWVisualize2025.Queue.server: 'Manual'

Scripts:
    start:
        User: '%TOOLS_DIR%\solidworks-accept-eula.ps1' # Runs at user login

Registry:
    HKLM:
        SOFTWARE\SolidWorks\Applications\PDMWorks Enterprise\Databases\Baja_Vault:
            DbName:
                Type:   'String'
                Value:  'Baja_Vault'

            DbServer:
                Type:   'String'
                Value:  '%BAJA_LICENSE%'

            ServerLoc:
                Type:   'String'
                Value:  '%BAJA_LICENSE%'

            ShellRoot:
                Type:   'String'
                Value:  '%BAJA_LICENSE%'
